GET http://localhost:3000/user-api/users


#######

GET http://localhost:3000/author-api


#######

GET http://localhost:3000/admin-api



###create author
POST http://localhost:3000/author-api/author
Content-Type: application/json

{
    "role":"author",
    "firstName":"author1",
    "lastName":"author1",
    "email":"author1@gmail.com",
    "profileImageUrl":"author image",
    "isActive":true

}


###create user

POST http://localhost:3000/user-api/user
Content-Type: application/json

{
    "role":"user",
    "firstName":"user1",
    "lastName":"user1",
    "email":"user1@gmail.com",
    "profileImageUrl":"user 1",
    "isActive":true

}




####### create article
POST http://localhost:3000/author-api/article
Content-Type: application/json

{

 "authorData":{
     "name":"author1",
     "email":"author1@gmail.com",
     "profileImageUrl":"author1 image"
 },
"articleId":"{{$timestamp}}",
"title":"Fundamentals of java-script",
"category":"test",
"content":"lorem ipsum dolar sit amet",
"dateOfCreation":"{{$datetime iso8601}}",
"dateOfModification":"{{$datetime iso8601}}",
"comments":[],
"isArticleActive":true
}


###edit article  by articleId
Put http://localhost:3000/author-api/article/articleId
Content-Type: application/json

{
 "_id":"68fbc35e381538728623c807",
 "authorData":{
     "name":"",
     "email":"",
     "profileImageUrl":""
 },
"articleId":"{{$timestamp}}",
"title":"Fundamentals of js",
"category":"programming",
"content":"lorem ipsum dolar sit amet",
"dateOfModification":"{{$datetime iso8601}}",
"comments":[],
"isArticleActive":true
}


###read all articles

GET  http://localhost:3000/author-api/articles




###delete article by articleId(softdelete)
PUT http://localhost:3000/author-api/articles/1761399315
Content-Type: application/json

{
 "_id":"68fbc35e381538728623c807",
 "authorData":{
     "name":"",
     "email":"",
     "profileImageUrl":""
 },
"articleId":"{{$timestamp}}",
"title":"Fundamentals of java-script",
"category":"test",
"content":"lorem ipsum dolar sit amet",
"dateOfCreation":"{{$datetime iso8601}}",
"dateOfModification":"{{$datetime iso8601}}",
"comments":[],
"isArticleActive":false
}



###post comment using articleId
put http://localhost:3000/user-api/comment/1761400044
Content-Type: application/json

{
    "nameOfUser":"user1",
    "comment":"article is good"
}